axon:
  max_gradients: 100
  max_workers: 10
  port: 8091
  remote_ip: 99.238.136.56
dendrite:
  do_backoff: true
  key_dim: 100
  max_backoff: 100
  pass_gradients: true
  stale_emit_filter: 10000
  timeout: 0.5
  topk: 10
metagraph:
  chain_endpoint: 206.189.254.5:12345
  stale_emit_filter: 10000
neuron:
  accumulation_interval: 5
  apply_remote_gradients: true
  batch_size_train: 3
  datapath: data
  learning_rate: 0.001
  log_interval: 10
  momentum: 0.98
  name: Adam
  sync_interval: 100
  trial_id: '1608300539'
  trial_path: data/adam/1608300539
nucleus:
  max_workers: 5
  queue_maxsize: 1000
  queue_timeout: 5
session:
  keyfile: ~/.bittensor/key
  keypair: '5DaQQ6umBFmZRmj5pDPK1oXz6NWWRGjngBJozLFQJSM3PAP8'
synapse:
  activation_function: gelu_new
  attn_pdrop: 0.1
  embd_pdrop: 0.1
  initializer_range: 0.02
  layer_norm_epsilon: 1.0e-05
  n_head: 2
  n_hidden: 3
  n_inner: null
  n_layer: 12
  resid_pdrop: 0.1
  summary_activation: null
  summary_first_dropout: 0.1
  summary_proj_to_labels: true
  summary_type: cls_index
  summary_use_proj: true