axon:
  local_port: 8091
  local_ip: 127.0.0.1
  use_upnpc: False
  max_workers: 10
  max_gradients: 100
receptor:
  pass_gradients: true
  timeout: 0.5
  do_backoff: true
  max_backoff: 100
  key_dim: 100
  stale_emit_filter: 10000
  topk: 10
metagraph:
  chain_endpoint: feynman.akira.bittensor.com:9944 # Test network
  stale_emit_filter: 10000
session:
  learning_rate: 0.001
  momentum: 0.98
  n_epochs: 1
  batch_size_train: 8
  sync_interval: 10
  log_interval: 10
  accumulation_interval: 1
  name: bert_nsp
  record_log: true
nucleus:
  max_workers: 5
  queue_maxsize: 10000
  queue_timeout: 5
neuron: # Make sure your coldkeyfile and hotkeyfile locations are correct!
  coldkeyfile: ~/.bittensor/wallets/default/coldkeypub.txt 
  hotkeyfile: ~/.bittensor/wallets/default/hotkeys/default# nucleus:
synapse:
  num_hidden_layers: 2
  num_attention_heads: 2
  n_block_filter: 100