jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run: sudo pip install codecov pytest grpcio-tools
      - run: sudo pip install pytest
      - python/save-cache
      - run:
          command: sudo python setup.py develop
          name: setup
      - run:
          command: pytest ./tests --full-trace
          name: test
orbs:
  python: circleci/python@0.1
version: 2.1
workflows:
  main:
    jobs:
      - build
