jobs:
  build:
    executor: python/default
    docker:
      - image: circleci/python:3.6.4 
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - python/install-packages:
          pkg-manager: pip
          pypi-cache: true
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - run:
        command: pip install --upgrade pip
        name: pipup 
      - run:
          command: sudo python setup.py develop
          name: setup
      - run:
          name: test
          command: |
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov
orbs:
  python: circleci/python@1.2.0
version: 2.1
workflows:
  main:
    jobs:
      - build
