version: 2.1

executors:
    bittensor-executor:
        docker:
          - image: bittensor/bittensor:latest

orbs:
  python: circleci/python@0.2.1
  shellcheck: circleci/shellcheck@2.0.0

jobs:
  "Build Bittensor":
    executor: bittensor-executor
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install -e .
          name: setup

  "Run Unit Tests":
    executor: bittensor-executor
    steps:
      - checkout
      - python/load-cache
      - run: pip install codecov pytest
      - run:
          name: "Run unit tests"
          command: pytest ./tests/unit_tests
      - run:
          name: "Code Coverage"
          command: codecov
  
  "Run Integration Tests":
    executor: bittensor-executor
    steps:
      - checkout
      - python/load-cache
      - run: pip install codecov pytest
      - run:
          name: "Run Localized CPU Integration tests"
          command: pytest ./tests/integration_tests/cpu_tests
      - run:
          name: "Code Coverage"
          command: codecov
  
  "Run Remote Peer Integration Tests":
    executor: bittensor-executor
    steps:
      - checkout
      - python/load-cache
      - run: pip install codecov pytest
      - run:
          name: Install Ngrok for TCP tunneling
          command: sudo wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip . && sudo unzip ngrok-stable-linux-amd64.zip -d /usr/local/bin
      - run:
          name: Run Ngrok
          command: ngrok tcp 

  "Push Production candidate to DockerHub":
    docker:
      - image: circleci/python:3.8.1
        auth: 
           username: $DOCKER_USER
           password: $DOCKERPASS
    steps:
      - checkout
      - python/load-cache
      - setup_remote_docker:
             version: 19.03.13
      - run:
          name: "Docker credentials"
          command: echo $DOCKERPASS | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: "Push production candidate"
          command: ./scripts/push_image.sh

workflows:
  main:
    jobs:
      - "Build Bittensor"
      - "Run Unit Tests":
              requires:
                - "Build Bittensor"
      - "Run Integration Tests":
              requires:
                - "Build Bittensor"
      - "Push Production candidate to DockerHub":
              requires:
                - "Build Bittensor"
                - "Run Unit Tests"
              filters:
                branches:
                  only:
                    - master
