jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pypi-cache: true
      - run:
          command: sudo python setup.py develop
          name: setup
      - run:
          name: test
          command: |
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov
orbs:
  python: circleci/python@1.2.0
version: 2.1
workflows:
  main:
    jobs:
      - build
