jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            if [[ $(pip show grpcio | grep Version) != *1.31* ]]; then
              git clone https://github.com/grpc/grpc --recurse-submodules
              cd grpc
              sudo pip install -r requirements.txt
              export GRPC_PYTHON_BUILD_WITH_CYTHON=1
              sudo pip install .
              cd -
            fi
          name: compile-grpc  # remove this command when v1.31 becomes available via pip install -r requirements.txt
      - run: sudo pip install codecov pytest grpcio-tools
      - run: sudo pip install pytest
      - python/save-cache
      - run:
          command: sudo python setup.py develop
          name: setup
orbs:
  python: circleci/python@0.1
version: 2.1
workflows:
  main:
    jobs:
      - build
