jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run: sudo pip install pytest
      - python/save-cache
      - run:
          command: sudo python setup.py develop
          name: setup
orbs:
  python: circleci/python@0.1
version: 2.1
workflows:
  main:
    jobs:
      - build
