jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run: sudo pip install codecov pytest grpcio-tools
      - run: sudo pip install pytest
      - python/save-cache
      - run:
          command: sudo python setup.py develop
          name: setup
      - run:
          command: pytest ./tests --full-trace
          name: test

      - run:
        name: Coverage
        command: |
          $HOME/.local/bin/coverage run -m pytest
          $HOME/.local/bin/coverage report
          $HOME/.local/bin/coverage html  # open htmlcov/index.html in a browser
      - store_artifacts:
        path: htmlcov
orbs:
  python: circleci/python@0.1
version: 2.1
workflows:
  main:
    jobs:
      - build
