version: 2.1

executors:
    bittensor-executor:
        docker:
          - image: bittensor/bittensor:latest

orbs:
  python: circleci/python@0.2.1

jobs:
  "Build Bittensor":
    executor: bittensor-executor
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install -e .
          name: setup

  "Run Unit Tests":
    executor: bittensor-executor
    steps:
      - checkout
      - python/load-cache
      - run: pip install codecov pytest
      - run:
          command: pytest ./tests
          name: tests
      - run:
          command: codecov
          name: codecov
  
  "Push Production candidate to DockerHub":
    docker:
      - image: circleci/python:3.8.1
        auth: 
           username: shibshib
           password: $DOCKERPASS
    steps:
      - checkout
      - python/load-cache
      - setup_remote_docker:
             version: 19.03.13
      - run:
          name: "Docker credentials"
          command: echo $DOCKERPASS | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: "Push production candidate"
          command: ./scripts/push_image.sh

workflows:
  main:
    jobs:
      - "Build Bittensor"
      - "Run Unit Tests":
              requires:
                - "Build Bittensor"
      - "Push Production candidate to DockerHub":
              requires:
                - "Build Bittensor"
                - "Run Unit Tests"
              filters:
                branches:
                  only:
                    - master
