wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: huggingface
    huggingface_version: 4.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1637700984
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      4: 3.8.12
      5: 0.12.0
      6: 4.5.1
      8:
      - 5
