version: 2
workflows:
  experiment-workflow:
    steps:
      -
        name: "CUDA Integration Tests"
        command: experiment.run_single_node
        params:
          command: pip install tensorboard torchvision transformers pytest loguru && pytest ./tests/integration_tests/gpu_tests/
          container: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime
          machineType: GPU+
