axon:
  local_port: 8091
  local_ip: 127.0.0.1
  use_upnpc: False
  max_workers: 10
  max_gradients: 100
receptor:
  pass_gradients: true
  timeout: 0.5
  do_backoff: true
  max_backoff: 100
  key_dim: 100
  stale_emit_filter: 10000
  topk: 10
metagraph:
  network: akira # Test network
  stale_emit_filter: 10000
miner:
  accumulation_interval: 5
  apply_remote_gradients: true
  batch_size_train: 1
  learning_rate: 0.001
  log_interval: 10
  momentum: 0.98
  sync_interval: 100
  record_log: true
nucleus:
  max_workers: 5
  queue_maxsize: 10000
  queue_timeout: 5
neuron: # Make sure your coldkeyfile and hotkeyfile locations are correct!
  coldkeyfile: ~/.bittensor/wallets/default/coldkeypub.txt 
  hotkeyfile: ~/.bittensor/wallets/default/hotkeys/default
synapse:
  num_hidden_layers: 2
  num_attention_heads: 2
  n_block_filter: 100