# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pushing Image to Docker

on: 
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # python -m pip install flake8 
        python -m pip install pytest cython
        if [ -f requirements.txt ]; then pip install -r requirements.txt --use-deprecated=legacy-resolver; fi
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build Bittensor
      run: |
        python -m pip install -e .
        ./scripts/create_wallet.sh
        ./scripts/build_protos.sh
    - name: Run Unit Tests
      run: pytest ./tests/unit_tests --cov=./tests/ --cov-append 
    - name: Run Integration Tests
      run: pytest ./tests/integration_tests
    - name: Run Miners
      run: python tests/miners/text/test_gpt2_exodus.py --cov=./tests/ --cov-append 
    - name: Run dataloader tests
      run: pytest ./tests/integration_tests/test_dataloader_ipfs.py --cov=./tests/ --cov-append 
    - name: Code Coverage
      run: codecov
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASS}}
    - name: Build and Push to Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: bittensor/bittensor:latest
